#!/bin/bash
LD_LIBRARY_PATH=/root/encoder/libfnr/src/.libs gunicorn --certfile=/etc/letsencrypt/live/memory-backend.nat-mcaleese.co.uk/fullchain.pem --keyfile=/etc/letsencrypt/live/memory-backend.nat-mcaleese.co.uk/privkey.pem  --bind 0.0.0.0:443 "$@" wordify.service:app
